spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    time-zone: Asia/Seoul
    h2:
      console:
        enabled: true
        path: /h2
    datasource:
      url: jdbc:h2:mem:test
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: false
      properties:
        hibernate:
          format_sql: true
    sql:
      init:
        data-locations: classpath*:db/h2/data.spl
    security:
  logging:
    level:
      org:
        springframework:
          orm:
            jpa: INFO
  server:
    servlet:
      encoding:
        force-response: true
  mail:
    address:
      admin: tbvjdngus@gmail.com
  jwt:
    key:
      secret: ${jwtSecret}
    access-token-expiration-minutes: 120
    refresh-token-expiration-minutes: 420
  marketo:
    marketoInstance: ${MarketoInstance}
    clientId: ${MarketoClientId}
    clientSecret: ${MarketoClientSecret}
    # for test #
  #  access-token-expiration-minutes: 1
  #  refresh-token-expiration-minutes: 2
